// <auto-generated />
using System;
using Algowars.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Algowars.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlgoWarsDbContext))]
    [Migration("20260615023526_AddSubmissionOutboxSteps")]
    partial class AddSubmissionOutboxSteps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Languages.LanguageVersionDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProgrammingLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("programming_language_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammingLanguageId");

                    b.ToTable("programming_language_versions");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Languages.ProgrammingLanguageDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("programming_languages");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Problems.CodeTemplateDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LanguageVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_version_id");

                    b.Property<Guid>("ProblemVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_version_id");

                    b.Property<string>("StarterCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("starter_code");

                    b.Property<string>("WrapperCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wrapper_code");

                    b.HasKey("Id");

                    b.HasIndex("ProblemVersionId");

                    b.ToTable("code_templates");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Problems.ProblemDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("problems");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Problems.ProblemVersionDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("MemoryLimitKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit_kb");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_ms");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.ToTable("problem_versions");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Problems.TestCaseDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_output");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<Guid>("ProblemVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_version_id");

                    b.HasKey("Id");

                    b.HasIndex("ProblemVersionId");

                    b.ToTable("test_cases");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Submissions.SubmissionDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("LanguageVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_version_id");

                    b.Property<Guid>("ProblemVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_version_id");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_code");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("submissions");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Submissions.SubmissionOutboxDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Step")
                        .HasColumnType("integer")
                        .HasColumnName("step");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id");

                    b.ToTable("submission_outbox_steps");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Submissions.SubmissionResultDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualOutput")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("actual_output");

                    b.Property<string>("CompileOutput")
                        .HasColumnType("text")
                        .HasColumnName("compile_output");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int?>("MemoryKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_kb");

                    b.Property<int?>("RuntimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_ms");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Stderr")
                        .HasColumnType("text")
                        .HasColumnName("stderr");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("submission_results");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Submissions.SubmissionTestCaseDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("submission_test_cases");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Users.UserDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sub");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("username");

                    b.Property<DateTime?>("UsernameLastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("username_last_changed_at");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Languages.LanguageVersionDataModel", b =>
                {
                    b.HasOne("Algowars.Infrastructure.Persistence.Entities.Languages.ProgrammingLanguageDataModel", "ProgrammingLanguage")
                        .WithMany("Versions")
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammingLanguage");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Problems.CodeTemplateDataModel", b =>
                {
                    b.HasOne("Algowars.Infrastructure.Persistence.Entities.Problems.ProblemVersionDataModel", "ProblemVersion")
                        .WithMany("CodeTemplates")
                        .HasForeignKey("ProblemVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemVersion");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Problems.ProblemVersionDataModel", b =>
                {
                    b.HasOne("Algowars.Infrastructure.Persistence.Entities.Problems.ProblemDataModel", "Problem")
                        .WithMany("Versions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Problems.TestCaseDataModel", b =>
                {
                    b.HasOne("Algowars.Infrastructure.Persistence.Entities.Problems.ProblemVersionDataModel", "ProblemVersion")
                        .WithMany("TestCases")
                        .HasForeignKey("ProblemVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemVersion");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Submissions.SubmissionResultDataModel", b =>
                {
                    b.HasOne("Algowars.Infrastructure.Persistence.Entities.Submissions.SubmissionDataModel", "Submission")
                        .WithMany("Results")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Submissions.SubmissionTestCaseDataModel", b =>
                {
                    b.HasOne("Algowars.Infrastructure.Persistence.Entities.Submissions.SubmissionDataModel", "Submission")
                        .WithMany("TestCases")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Languages.ProgrammingLanguageDataModel", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Problems.ProblemDataModel", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Problems.ProblemVersionDataModel", b =>
                {
                    b.Navigation("CodeTemplates");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("Algowars.Infrastructure.Persistence.Entities.Submissions.SubmissionDataModel", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
