// <auto-generated />
using System;
using Algowars.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Algowars.Infrastructure.Migrations
{
    [DbContext(typeof(AlgowarsDbContext))]
    [Migration("20260712032553_AddProblemTags")]
    partial class AddProblemTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Algowars.Domain.Languages.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Languages.Entities.LanguageVersionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Judge0Id")
                        .HasColumnType("integer")
                        .HasColumnName("judge0_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.Property<Guid>("language_id")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.HasKey("Id");

                    b.HasIndex("language_id");

                    b.ToTable("language_versions", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("MemoryLimit")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("question");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("problems", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("MemoryLimit")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("question");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("problem_id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_history", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemSetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("function_name");

                    b.Property<string>("InitialCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initial_code");

                    b.Property<Guid>("LanguageVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_version_id");

                    b.Property<Guid>("problem_id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_setups", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Submissions.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProblemSetupId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_setup_id");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("source_code");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Submissions.Entities.SubmissionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualOutput")
                        .HasColumnType("text")
                        .HasColumnName("actual_output");

                    b.Property<string>("CompileOutput")
                        .HasColumnType("text")
                        .HasColumnName("compile_output");

                    b.Property<int?>("MemoryUsed")
                        .HasColumnType("integer")
                        .HasColumnName("memory_used");

                    b.Property<int?>("Runtime")
                        .HasColumnType("integer")
                        .HasColumnName("runtime");

                    b.Property<string>("StandardError")
                        .HasColumnType("text")
                        .HasColumnName("standard_error");

                    b.Property<string>("StandardOutput")
                        .HasColumnType("text")
                        .HasColumnName("standard_output");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<string>("evaluation_id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("evaluation_id");

                    b.Property<string>("execution_id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("execution_id");

                    b.Property<Guid>("submission_id")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id");

                    b.HasIndex("submission_id");

                    b.ToTable("submission_results", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("test_suite_id")
                        .HasColumnType("uuid")
                        .HasColumnName("test_suite_id");

                    b.HasKey("Id");

                    b.HasIndex("test_suite_id");

                    b.ToTable("test_cases", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCaseExpectedOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value_type");

                    b.Property<Guid>("test_case_id")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.HasKey("Id");

                    b.HasIndex("test_case_id");

                    b.ToTable("test_case_expected_outputs", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCaseInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value_type");

                    b.Property<Guid>("test_case_id")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.HasKey("Id");

                    b.HasIndex("test_case_id");

                    b.ToTable("test_case_inputs", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("test_suites", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sub");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.Property<DateTime?>("UsernameLastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("username_last_changed_at");

                    b.HasKey("Id");

                    b.HasIndex("Sub")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProblemProblemTag", b =>
                {
                    b.Property<Guid>("ProblemsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("ProblemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("problem_tags", (string)null);
                });

            modelBuilder.Entity("problem_setup_test_suites", b =>
                {
                    b.Property<Guid>("problem_setup_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("test_suite_id")
                        .HasColumnType("uuid");

                    b.HasKey("problem_setup_id", "test_suite_id");

                    b.HasIndex("test_suite_id");

                    b.ToTable("problem_setup_test_suites", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Languages.Entities.LanguageVersionEntry", b =>
                {
                    b.HasOne("Algowars.Domain.Languages.Entities.Language", null)
                        .WithMany("Versions")
                        .HasForeignKey("language_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.Problem", b =>
                {
                    b.OwnsOne("Algowars.Domain.Problems.ValueObjects.Slug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("ProblemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("slug");

                            b1.HasKey("ProblemId");

                            b1.ToTable("problems");

                            b1.WithOwner()
                                .HasForeignKey("ProblemId");
                        });

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemHistory", b =>
                {
                    b.HasOne("Algowars.Domain.Problems.Entities.Problem", null)
                        .WithMany("History")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemSetup", b =>
                {
                    b.HasOne("Algowars.Domain.Problems.Entities.Problem", null)
                        .WithMany("Setups")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Submissions.Entities.SubmissionResult", b =>
                {
                    b.HasOne("Algowars.Domain.Submissions.Entities.Submission", null)
                        .WithMany("Results")
                        .HasForeignKey("submission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCase", b =>
                {
                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestSuite", null)
                        .WithMany("TestCases")
                        .HasForeignKey("test_suite_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCaseExpectedOutput", b =>
                {
                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestCase", null)
                        .WithMany("ExpectedOutputs")
                        .HasForeignKey("test_case_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCaseInput", b =>
                {
                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestCase", null)
                        .WithMany("Inputs")
                        .HasForeignKey("test_case_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProblemProblemTag", b =>
                {
                    b.HasOne("Algowars.Domain.Problems.Entities.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.Problems.Entities.ProblemTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("problem_setup_test_suites", b =>
                {
                    b.HasOne("Algowars.Domain.Problems.Entities.ProblemSetup", null)
                        .WithMany()
                        .HasForeignKey("problem_setup_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestSuite", null)
                        .WithMany()
                        .HasForeignKey("test_suite_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Languages.Entities.Language", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.Problem", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Setups");
                });

            modelBuilder.Entity("Algowars.Domain.Submissions.Entities.Submission", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCase", b =>
                {
                    b.Navigation("ExpectedOutputs");

                    b.Navigation("Inputs");
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestSuite", b =>
                {
                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
