// <auto-generated />
using System;
using Algowars.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Algowars.Infrastructure.Migrations
{
    [DbContext(typeof(AlgowarsDbContext))]
    [Migration("20260621220618_MigrateOldDatabase")]
    partial class MigrateOldDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("MemoryLimit")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("question");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("problems", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("MemoryLimit")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("question");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("problem_id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_history", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemSetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("function_name");

                    b.Property<string>("InitialCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initial_code");

                    b.Property<Guid>("LanguageVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_version_id");

                    b.Property<Guid>("problem_id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_setups", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("test_suite_id")
                        .HasColumnType("uuid")
                        .HasColumnName("test_suite_id");

                    b.HasKey("Id");

                    b.HasIndex("test_suite_id");

                    b.ToTable("test_cases", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCaseExpectedOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value_type");

                    b.Property<Guid>("test_case_id")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.HasKey("Id");

                    b.HasIndex("test_case_id");

                    b.ToTable("test_case_expected_outputs", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCaseInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value_type");

                    b.Property<Guid>("test_case_id")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.HasKey("Id");

                    b.HasIndex("test_case_id");

                    b.ToTable("test_case_inputs", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("test_suites", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sub");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.Property<DateTime?>("UsernameLastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("username_last_changed_at");

                    b.HasKey("Id");

                    b.HasIndex("Sub")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("problem_setup_test_suites", b =>
                {
                    b.Property<Guid>("problem_setup_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("test_suite_id")
                        .HasColumnType("uuid");

                    b.HasKey("problem_setup_id", "test_suite_id");

                    b.HasIndex("test_suite_id");

                    b.ToTable("problem_setup_test_suites", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemHistory", b =>
                {
                    b.HasOne("Algowars.Domain.Problems.Entities.Problem", null)
                        .WithMany("History")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemSetup", b =>
                {
                    b.HasOne("Algowars.Domain.Problems.Entities.Problem", null)
                        .WithMany("Setups")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCase", b =>
                {
                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestSuite", null)
                        .WithMany("TestCases")
                        .HasForeignKey("test_suite_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCaseExpectedOutput", b =>
                {
                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestCase", null)
                        .WithMany("ExpectedOutputs")
                        .HasForeignKey("test_case_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCaseInput", b =>
                {
                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestCase", null)
                        .WithMany("Inputs")
                        .HasForeignKey("test_case_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("problem_setup_test_suites", b =>
                {
                    b.HasOne("Algowars.Domain.Problems.Entities.ProblemSetup", null)
                        .WithMany()
                        .HasForeignKey("problem_setup_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestSuite", null)
                        .WithMany()
                        .HasForeignKey("test_suite_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.Problem", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Setups");
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCase", b =>
                {
                    b.Navigation("ExpectedOutputs");

                    b.Navigation("Inputs");
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestSuite", b =>
                {
                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
