// <auto-generated />
using System;
using Algowars.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Algowars.Infrastructure.Migrations
{
    [DbContext(typeof(AlgowarsDbContext))]
    partial class AlgowarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Algowars.Domain.Authorization.Rbac.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Authorization.Rbac.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Authorization.Rbac.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Authorization.Rbac.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effect");

                    b.HasKey("PermissionId", "role_id");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_role_permissions_permission_id");

                    b.HasIndex("role_id")
                        .HasDatabaseName("IX_role_permissions_role_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Authorization.Security.Entities.SecurityRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetectionEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PermissionCode");

                    b.ToTable("security_restrictions", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.ExecutionPipelines.Entities.ExecutionPipelineStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPolling")
                        .HasColumnType("boolean")
                        .HasColumnName("is_polling");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<int>("StepType")
                        .HasColumnType("integer")
                        .HasColumnName("step_type");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<Guid>("pipeline_id")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_id");

                    b.HasKey("Id");

                    b.HasIndex("pipeline_id");

                    b.ToTable("execution_pipeline_steps", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.ExecutionPipelines.ExecutionPipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("execution_pipelines", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Languages.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Languages.Entities.LanguageVersionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Judge0Id")
                        .HasColumnType("integer")
                        .HasColumnName("judge0_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.Property<Guid>("language_id")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.HasKey("Id");

                    b.HasIndex("language_id");

                    b.ToTable("language_versions", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("MemoryLimit")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("question");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("problems", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("MemoryLimit")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("question");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("problem_id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_history", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemSetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("function_name");

                    b.Property<string>("InitialCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initial_code");

                    b.Property<Guid>("LanguageVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_version_id");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_id");

                    b.Property<Guid>("problem_id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("LanguageVersionId");

                    b.HasIndex("PipelineId");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_setups", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.SubmissionJobs.Entities.SubmissionJobAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid>("PipelineStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_step_id");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("text")
                        .HasColumnName("request_payload");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("text")
                        .HasColumnName("response_payload");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("job_id")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.HasKey("Id");

                    b.HasIndex("PipelineStepId");

                    b.HasIndex("job_id");

                    b.ToTable("submission_job_attempts", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.SubmissionJobs.SubmissionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_step_id");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStepId");

                    b.HasIndex("PipelineId");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("submission_jobs", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Submissions.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProblemSetupId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_setup_id");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("source_code");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProblemSetupId");

                    b.HasIndex("UserId");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Submissions.Entities.SubmissionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualOutput")
                        .HasColumnType("text")
                        .HasColumnName("actual_output");

                    b.Property<string>("CompileOutput")
                        .HasColumnType("text")
                        .HasColumnName("compile_output");

                    b.Property<int?>("MemoryUsed")
                        .HasColumnType("integer")
                        .HasColumnName("memory_used");

                    b.Property<int?>("Runtime")
                        .HasColumnType("integer")
                        .HasColumnName("runtime");

                    b.Property<string>("StandardError")
                        .HasColumnType("text")
                        .HasColumnName("standard_error");

                    b.Property<string>("StandardOutput")
                        .HasColumnType("text")
                        .HasColumnName("standard_output");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<string>("evaluation_id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("evaluation_id");

                    b.Property<string>("execution_id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("execution_id");

                    b.Property<Guid>("submission_id")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.HasIndex("submission_id");

                    b.ToTable("submission_results", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("test_suite_id")
                        .HasColumnType("uuid")
                        .HasColumnName("test_suite_id");

                    b.HasKey("Id");

                    b.HasIndex("test_suite_id");

                    b.ToTable("test_cases", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCaseExpectedOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value_type");

                    b.Property<Guid>("test_case_id")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.HasKey("Id");

                    b.HasIndex("test_case_id");

                    b.ToTable("test_case_expected_outputs", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCaseInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value_type");

                    b.Property<Guid>("test_case_id")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.HasKey("Id");

                    b.HasIndex("test_case_id");

                    b.ToTable("test_case_inputs", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("test_suites", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sub");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.Property<DateTime?>("UsernameLastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("username_last_changed_at");

                    b.HasKey("Id");

                    b.HasIndex("Sub")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Algowars.Infrastructure.ExecutionEngine.Assert.AssertStepConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("case_sensitive");

                    b.Property<Guid>("PipelineStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_step_id");

                    b.Property<int>("Strategy")
                        .HasColumnType("integer")
                        .HasColumnName("strategy");

                    b.Property<decimal?>("Tolerance")
                        .HasColumnType("numeric")
                        .HasColumnName("tolerance");

                    b.HasKey("Id");

                    b.HasIndex("PipelineStepId")
                        .IsUnique();

                    b.ToTable("assert_step_configurations", (string)null);
                });

            modelBuilder.Entity("Algowars.Infrastructure.ExecutionEngine.Judge0.Judge0StepConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DefaultTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("default_timeout_seconds");

                    b.Property<bool>("IsEncoded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_encoded");

                    b.Property<Guid>("PipelineStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_step_id");

                    b.Property<bool>("ShouldWait")
                        .HasColumnType("boolean")
                        .HasColumnName("should_wait");

                    b.Property<bool>("StripWhitespace")
                        .HasColumnType("boolean")
                        .HasColumnName("strip_whitespace");

                    b.HasKey("Id");

                    b.HasIndex("PipelineStepId")
                        .IsUnique();

                    b.ToTable("judge0_step_configurations", (string)null);
                });

            modelBuilder.Entity("ProblemProblemTag", b =>
                {
                    b.Property<Guid>("ProblemsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("ProblemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("problem_tags", (string)null);
                });

            modelBuilder.Entity("group_roles", b =>
                {
                    b.Property<Guid>("group_id")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("group_id", "role_id");

                    b.HasIndex("role_id")
                        .HasDatabaseName("IX_group_roles_role_id");

                    b.ToTable("group_roles", (string)null);
                });

            modelBuilder.Entity("problem_setup_test_suites", b =>
                {
                    b.Property<Guid>("problem_setup_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("test_suite_id")
                        .HasColumnType("uuid");

                    b.HasKey("problem_setup_id", "test_suite_id");

                    b.HasIndex("test_suite_id");

                    b.ToTable("problem_setup_test_suites", (string)null);
                });

            modelBuilder.Entity("user_groups", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("group_id")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.HasKey("user_id", "group_id");

                    b.HasIndex("group_id")
                        .HasDatabaseName("IX_user_groups_group_id");

                    b.ToTable("user_groups", (string)null);
                });

            modelBuilder.Entity("Algowars.Domain.Authorization.Rbac.Entities.RolePermission", b =>
                {
                    b.HasOne("Algowars.Domain.Authorization.Rbac.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.Authorization.Rbac.Entities.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.ExecutionPipelines.Entities.ExecutionPipelineStep", b =>
                {
                    b.HasOne("Algowars.Domain.ExecutionPipelines.ExecutionPipeline", null)
                        .WithMany("Steps")
                        .HasForeignKey("pipeline_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Languages.Entities.LanguageVersionEntry", b =>
                {
                    b.HasOne("Algowars.Domain.Languages.Entities.Language", null)
                        .WithMany("Versions")
                        .HasForeignKey("language_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.Problem", b =>
                {
                    b.HasOne("Algowars.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Algowars.Domain.Problems.ValueObjects.Slug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("ProblemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("slug");

                            b1.HasKey("ProblemId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("problems");

                            b1.WithOwner()
                                .HasForeignKey("ProblemId");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemHistory", b =>
                {
                    b.HasOne("Algowars.Domain.Problems.Entities.Problem", null)
                        .WithMany("History")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.ProblemSetup", b =>
                {
                    b.HasOne("Algowars.Domain.Languages.Entities.LanguageVersionEntry", null)
                        .WithMany()
                        .HasForeignKey("LanguageVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.ExecutionPipelines.ExecutionPipeline", null)
                        .WithMany()
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.Problems.Entities.Problem", null)
                        .WithMany("Setups")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.SubmissionJobs.Entities.SubmissionJobAttempt", b =>
                {
                    b.HasOne("Algowars.Domain.ExecutionPipelines.Entities.ExecutionPipelineStep", null)
                        .WithMany()
                        .HasForeignKey("PipelineStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.SubmissionJobs.SubmissionJob", null)
                        .WithMany("Attempts")
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.SubmissionJobs.SubmissionJob", b =>
                {
                    b.HasOne("Algowars.Domain.ExecutionPipelines.Entities.ExecutionPipelineStep", null)
                        .WithMany()
                        .HasForeignKey("CurrentStepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Algowars.Domain.ExecutionPipelines.ExecutionPipeline", null)
                        .WithMany()
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.Submissions.Entities.Submission", null)
                        .WithOne()
                        .HasForeignKey("Algowars.Domain.SubmissionJobs.SubmissionJob", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Submissions.Entities.Submission", b =>
                {
                    b.HasOne("Algowars.Domain.Problems.Entities.ProblemSetup", null)
                        .WithMany()
                        .HasForeignKey("ProblemSetupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Submissions.Entities.SubmissionResult", b =>
                {
                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestCase", null)
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.Submissions.Entities.Submission", null)
                        .WithMany("Results")
                        .HasForeignKey("submission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCase", b =>
                {
                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestSuite", null)
                        .WithMany("TestCases")
                        .HasForeignKey("test_suite_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCaseExpectedOutput", b =>
                {
                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestCase", null)
                        .WithMany("ExpectedOutputs")
                        .HasForeignKey("test_case_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCaseInput", b =>
                {
                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestCase", null)
                        .WithMany("Inputs")
                        .HasForeignKey("test_case_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Infrastructure.ExecutionEngine.Assert.AssertStepConfiguration", b =>
                {
                    b.HasOne("Algowars.Domain.ExecutionPipelines.Entities.ExecutionPipelineStep", null)
                        .WithOne()
                        .HasForeignKey("Algowars.Infrastructure.ExecutionEngine.Assert.AssertStepConfiguration", "PipelineStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Infrastructure.ExecutionEngine.Judge0.Judge0StepConfiguration", b =>
                {
                    b.HasOne("Algowars.Domain.ExecutionPipelines.Entities.ExecutionPipelineStep", null)
                        .WithOne()
                        .HasForeignKey("Algowars.Infrastructure.ExecutionEngine.Judge0.Judge0StepConfiguration", "PipelineStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProblemProblemTag", b =>
                {
                    b.HasOne("Algowars.Domain.Problems.Entities.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.Problems.Entities.ProblemTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("group_roles", b =>
                {
                    b.HasOne("Algowars.Domain.Authorization.Rbac.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.Authorization.Rbac.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("problem_setup_test_suites", b =>
                {
                    b.HasOne("Algowars.Domain.Problems.Entities.ProblemSetup", null)
                        .WithMany()
                        .HasForeignKey("problem_setup_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.TestSuites.Entities.TestSuite", null)
                        .WithMany()
                        .HasForeignKey("test_suite_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("user_groups", b =>
                {
                    b.HasOne("Algowars.Domain.Authorization.Rbac.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Algowars.Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Algowars.Domain.Authorization.Rbac.Entities.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Algowars.Domain.ExecutionPipelines.ExecutionPipeline", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Algowars.Domain.Languages.Entities.Language", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Algowars.Domain.Problems.Entities.Problem", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Setups");
                });

            modelBuilder.Entity("Algowars.Domain.SubmissionJobs.SubmissionJob", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Algowars.Domain.Submissions.Entities.Submission", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestCase", b =>
                {
                    b.Navigation("ExpectedOutputs");

                    b.Navigation("Inputs");
                });

            modelBuilder.Entity("Algowars.Domain.TestSuites.Entities.TestSuite", b =>
                {
                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
